#!/bin/bash

DEST_DIR=$1
LOG=simple_disk.log

echo "simple_disk"
echo "==========="

echo ""
echo "Part of Simple-Slurm-Tools"
echo "https://github.com/megatron-uk/Simple-Slurm-Tools"
echo ""

echo "Target directory: ${DEST_DIR}"
if [ -d "${DEST_DIR}" ]
then
	echo "Target: Found"
else
	echo "Target: Not found, or not accessible!"
fi

echo ""
echo "Generating Directory Listing - please wait..."
ls -l -k -A -R ${DEST_DIR} | grep -v "total " | grep -v ^d | strings > ${LOG}

echo ""
echo "Extracting stats - please wait..."

# Get total number of files
TOTAL_FILES=`wc -l ${LOG} | awk '{print $1}'`
echo "- $TOTAL_FILES total files"

# Get total file size
TOTAL_BYTES=0
cat ${LOG} |  grep -v ^/ | awk '{print $5}' > ${LOG}.sub.bytes
while read file_bytes 
do
	TOTAL_BYTES=$(($TOTAL_BYTES + $file_bytes))
done < ${LOG}.sub.bytes
echo "- $TOTAL_BYTES total bytes"

# Get list of unique usernames
cat ${LOG} | grep -v ^/ | awk '{print $3}' | sort | uniq > ${LOG}.sub.users
TOTAL_USERS=`wc -l ${LOG}.sub.users | awk '{print $1}'`
echo "- $TOTAL_USERS users"

# For each user
echo ""
echo "Extracting per-user stats - please wait..."
cat ${LOG}.sub.users | while read u
do
	grep " $u " ${LOG} > "${LOG}.sub.user.$u"

	# How many files have the created
	TOTAL_USER_FILES=`wc -l ${LOG}.sub.user.$u | awk '{print $1}'`
	echo "- $u"
	echo "-- $TOTAL_USER_FILES files"
	
	# How much disk space have they used
	cat ${LOG}.sub.user.$u | awk '{print $5}' > ${LOG}.sub.user.$u.bytes
	TOTAL_BYTES=0
	while read file_bytes
	do
		TOTAL_BYTES=$(($TOTAL_BYTES + $file_bytes))
	done < ${LOG}.sub.user.$u.bytes

	echo "-- $TOTAL_BYTES bytes"
	echo ""
done

rm -v ${LOG}.sub.*
rm -v ${LOG}.sub
#rm -v ${LOG}
